### ISSUE TITLE
Formatting performance

### ISSUE THREAD

**Issue by andys8** [natefaubion/purescript-tidy#50] opened 2021-08-18 21:39 UTC
Hey 😀 First of all, thanks for working on this. This is such a promising project. I do also know that this is super early phase and the ticket issue raised here might _not be the most relevant_ as of today. Still I did want to share my findings and start discussion.

## Issue

Currently performance seems to be significantly slower than `purty`.

### Example: [`Article.purs` from `purescript-react-realworld`](https://github.com/jonasbuntinx/purescript-react-realworld/blob/master/src/Conduit/Page/Article.purs) 

Average example with 421 lines of code.

```shell
hyperfine "purty --write Article.purs" "purs-tidy format-in-place Article.purs"

Benchmark #1: purty --write Article.purs
  Time (mean ± σ):      54.4 ms ±  14.5 ms    [User: 78.6 ms, System: 93.8 ms]
  Range (min … max):    30.9 ms …  82.0 ms    52 runs

Benchmark #2: purs-tidy format-in-place Article.purs
  Time (mean ± σ):      1.005 s ±  0.122 s    [User: 2.656 s, System: 0.201 s]
  Range (min … max):    0.790 s …  1.207 s    10 runs

Summary
  'purty --write Article.purs' ran
   18.49 ± 5.40 times faster than 'purs-tidy format-in-place Article.purs'
```

### Example: Startup

Printing the version takes `200ms+`. This might show that node upstart and loading dependencies are already taking up a good amount of time.

```shell
hyperfine "purty version" "purs-tidy --version"
Benchmark #1: purty version
  Time (mean ± σ):      16.3 ms ±   2.6 ms    [User: 6.6 ms, System: 8.9 ms]
  Range (min … max):    11.2 ms …  20.5 ms    182 runs

Benchmark #2: purs-tidy --version
  Time (mean ± σ):     213.6 ms ±  18.4 ms    [User: 234.0 ms, System: 19.4 ms]
  Range (min … max):   190.6 ms … 245.6 ms    13 runs

Summary
  'purty version' ran
   13.10 ± 2.37 times faster than 'purs-tidy --version'
```

## Why is performance an issue?

I do think once performance takes a certain amount of time, developer experience feels sluggish and it becomes an issue.
For me personally `500 ms` is a threshold, because it is the [hardcoded timeout in CoC (Vim)](https://github.com/neoclide/coc.nvim/blob/9c54590c6dd37f06a27768a5c3e22615795a0ae9/src/handler/format.ts#L48-L51). If formatting takes longer, an error will be shown and the results are rejected. There are workarounds (see CoC issues), but it does highlight the issue.

## Info

```
node v16.5.0
Purty v7.0.0
purs-tidy 0.4.1
System x86_64 Linux 5.4.124-1-MANJARO i5-8265U 32GB
```

**Comment by andys8** [comment] 2021-08-18 21:59
## Dead Code Elimination

Applying [zephy](https://github.com/coot/zephyr) to the `output` folder shaved off `60 ms` for `--version`.

 ```
hyperfine  --warmup 1 "./bin/index.js --version" "./bin/index-dce.js --version"

Benchmark #1: ./bin/index.js --version
  Time (mean ± σ):     183.5 ms ±   9.8 ms    [User: 202.4 ms, System: 16.7 ms]
  Range (min … max):   177.1 ms … 207.6 ms    14 runs

Benchmark #2: ./bin/index-dce.js --version
  Time (mean ± σ):     117.9 ms ±   1.6 ms    [User: 128.6 ms, System: 14.2 ms]
  Range (min … max):   115.9 ms … 122.6 ms    23 runs

Summary
  './bin/index-dce.js --version' ran
    1.56 ± 0.09 times faster than './bin/index.js --version'
```

```
spago -x ./bin/spago.dhall build -u "--codegen corefn"
zephyr Main
# Change ./bin/index.js to use dce-output
```

**Comment by natefaubion** [comment] 2021-08-18 22:02
Purty is written in Haskell and compiles to native code, whereas Tidy is a PS library and runs on Node. There isn't going to be a way for Tidy to rival Purty in performance until we get a very fast native backend for PureScript. Unfortunately, because each run of Node is going to yield a cold JIT, it's going to be quite unavoidably slow!

**Comment by natefaubion** [comment] 2021-08-18 22:05
I'm not opposed to running zephyr DCE on releases if it helps. Unfortunately we can't bundle though due to how node-workerbees operates.

**Comment by andys8** [comment] 2021-08-18 22:16
Thanks for these answers.

> Unfortunately we can't bundle though due to how node-workerbees operates.

Could you elaborate this one? I was looking into how `purescript-language-server` is setup, and saw that the project leverages [`spago bundle-app`](https://github.com/nwolverson/purescript-language-server/blob/babe6bb0fbdf167858e3db9b70fda0c1ac6630b3/package.json#L25)

**Comment by natefaubion** [comment] 2021-08-18 22:23
`node-workerbees` is a nice hack for using node's `worker_threads` API in what appears to be a first-class way. `format-in-place` leverages multiple threads to format in parallel. Unfortunately the hack requires unbundled output (so it can require output modules directly from the FFI).

Just as a point of comparison, with 4 workers on my 6 year old laptop, tidy can format our work codebase (~2000 modules) in around 10-12s, so it definitely improves quite a lot the more work is done since the JIT can warm up. When formatting a single file however, it's probably going to mostly run in interpreted mode in V8, which is very bad for PureScript 😄 😭.

**Comment by andys8** [comment] 2021-08-18 22:34
Interesting, didn't know about that library :) 

Other ideas regarding performance: `purescipt-language-server` could directly add a dependency on `purs-tidy` and call the function instead of forking a process. This comes with other downsides like the coupling of dependencies and versions, but this seems to be what is done in `haskell-language-server`. It would be interesting to see the impact.

Nonetheless, I think node itself and loading dependencies is one part, but in addition there might be other bottlenecks.

A better comparison might be [`pose`](https://github.com/rowtype-yoga/pose), because it's implemented in node with the same approach (but also [bundling](https://github.com/rowtype-yoga/pose/blob/03cad6c80d5380e78282e4df074ec03357fb7124/packages/prettier-plugin-purescript/package.json#L14))
 
```
hyperfine "prettier --parser purescript --write src/Conduit/Page/Article.purs"
Benchmark #1: prettier --parser purescript --write src/Conduit/Page/Article.purs
  Time (mean ± σ):     409.5 ms ±  33.5 ms    [User: 538.9 ms, System: 30.3 ms]
  Range (min … max):   377.0 ms … 482.9 ms    10 runs
```

**Comment by natefaubion** [comment] 2021-08-18 22:42
I believe `pose` is largely a port of `purty` to PureScript, and you can see a slowdown factor of around 10x, which is about what I'd expect.

I don't think `tidy` will ever be as fast as `pose` because it supports dynamic width formatting, which adds an extra layer through `purescript-dodo-printer`. Even using the default settings, which don't use dynamic width formatting, it still has to go through dodo's printing interpreter. That's another thing that will be heavily affected by JIT. Dodo's printer is really fast _when optimized_, but probably adds a good chunk of overhead when in the baseline interpreter.

**Comment by natefaubion** [comment] 2021-08-19 15:37
It may be possible to bundle if we actually make _two_ bundles (one for main, and one for the worker), and then add some unsafe primitives to workerbees.

**Comment by natefaubion** [comment] 2021-08-20 00:11
Can you also time using `purs-tidy format` over stdin vs format-in-place with a single file?

**Comment by natefaubion** [comment] 2021-08-20 01:08
I can confirm that the worker startup is _significant_ given current circumstances. I expect that it's reading modules and instantiating everything anew for every worker. For a single, slow file I was able to cut time by 30% by avoiding workers.

**Comment by natefaubion** [comment] 2021-08-21 13:26
I can also confirm that bundling has a significant effect on simple commands like `--version`. I'll see what I can do to get a bundled version working.

**Comment by natefaubion** [comment] 2021-08-21 16:36
I've published 0.4.2 which has a bundled main and worker. Additionally it only uses workers when the number of files to format is greater than --threads * 2. Would you mind rerunning your tests? In my testing it's quite a bit faster!

**Comment by andys8** [comment] 2021-08-21 17:06
Thanks so much for your effort and looking into performance. I'm on a short vacation, but I'll definitely give it a shot when I'm back.

**Comment by natefaubion** [comment] 2021-08-21 17:14
For reference, on my machine, that Article.purs went from 1.098s on 0.4.2 to 431.2ms on 0.4.2!

**Comment by natefaubion** [comment] 2021-08-21 20:21
For more definitive timings (all with 3 warmup runs):
```
Benchmark #1: purty Article.purs --write
  Time (mean ± σ):     111.3 ms ±   7.3 ms    [User: 147.1 ms, System: 54.4 ms]
  Range (min … max):   100.3 ms … 127.9 ms    25 runs

Benchmark #1: purs-tidy format-in-place Article.purs
  Time (mean ± σ):     435.9 ms ±   6.4 ms    [User: 547.0 ms, System: 29.1 ms]
  Range (min … max):   426.8 ms … 444.7 ms    10 runs

Benchmark #1: npx prettier --parser purescript --write Article.purs
  Time (mean ± σ):     952.6 ms ±  14.6 ms    [User: 1.049 s, System: 0.116 s]
  Range (min … max):   927.4 ms … 975.8 ms    10 runs
```

In #53 I added support for timing information for _just_ formatting. `prettier` supports this already. Unfortunately I can't `hyperfine` this specifically, so I just ran it 10x and took the mean:

```
tidy: 206ms
pose: 247ms
```

So it looks like _a lot_ of the time in both of this is just startup, where `prettier` likely has a significantly weightier startup cost now. In my testing `tidy` is a little bit faster than `pose`, but not by that much.

I'm going to close this for now since I think it addresses the obvious startup issue. I'd still love to hear what timings you get on your machine (since it seems to be quite a bit faster than mine!).

**Closed by natefaubion** 2021-08-21 20:21 UTC

**Comment by natefaubion** [comment] 2021-08-21 20:33
Additionally, to illustrate how much difference JIT makes, the parser has a bench program (this is just parse time, `pose` and `tidy` use the same parser):
```
Benchmarking Article.purs
mean   = 36.30 ms
stddev = 18.34 ms
min    = 28.45 ms
max    = 179.84 ms
```

So regardless, most of the "formatting" time is actually going to the parser, since it's only being run once.

**Comment by andys8** [comment] 2021-08-23 16:56
Wow, the results are really impressive!


## `purs-tidy` v0.4.5

```shell
Benchmark #1: purs-tidy format-in-place src/Conduit/Page/Article.purs
  Time (mean ± σ):     332.5 ms ±  28.7 ms    [User: 446.6 ms, System: 23.5 ms]
  Range (min … max):   305.2 ms … 399.5 ms    10 runs
```

```shell
hyperfine "purs-tidy --version"
Benchmark #1: purs-tidy --version
  Time (mean ± σ):      62.5 ms ±   4.2 ms    [User: 55.7 ms, System: 8.0 ms]
  Range (min … max):    61.0 ms …  85.6 ms    33 runs
```

**Comment by natefaubion** [comment] 2021-08-23 17:13
> I wouldn't compare pose with npx. It does add additional overhead compared to a globally installed prettier.

That's a significant difference (I was just using the incantation from pose's website).
